CREATE TABLE APP_USER(
   idUser VARCHAR(30),
   name VARCHAR(20) NOT NULL,
   forname VARCHAR(20) NOT NULL,
   password VARCHAR(30) NOT NULL,
   PRIMARY KEY(idUser)
);

CREATE TABLE COMPANY(
   idUser VARCHAR(30),
   PRIMARY KEY(idUser),
   FOREIGN KEY(idUser) REFERENCES APP_USER(idUser)
);

CREATE TABLE STUDENT(
   idUser VARCHAR(30),
   apprenticeship NUMBER(1) NOT NULL,
   internship NUMBER(1) NOT NULL,
   PRIMARY KEY(idUser),
   FOREIGN KEY(idUser) REFERENCES APP_USER(idUser)
);

CREATE TABLE PROJECT(
   Id_PROJECT COUNTER,
   realisation_year DATE NOT NULL,
   PRIMARY KEY(Id_PROJECT)
);

CREATE TABLE CV(
   idTesttt VARCHAR(50),
   idUser VARCHAR(30) NOT NULL,
   PRIMARY KEY(idTesttt),
   FOREIGN KEY(idUser) REFERENCES STUDENT(idUser)
);

CREATE TABLE PROFILE_PICTURE(
   Id_PROFILE_PICTURE COUNTER,
   imageBlob ,
   idUser VARCHAR(30) NOT NULL,
   PRIMARY KEY(Id_PROFILE_PICTURE),
   FOREIGN KEY(idUser) REFERENCES STUDENT(idUser)
);

CREATE TABLE JOB_OFFER(
   Id_JOB_OFFER COUNTER,
   offerType BYTE NOT NULL,
   idUser VARCHAR(30) NOT NULL,
   PRIMARY KEY(Id_JOB_OFFER),
   FOREIGN KEY(idUser) REFERENCES COMPANY(idUser)
);

CREATE TABLE INDUSTRY(
   Id_INDUSTRY COUNTER,
   PRIMARY KEY(Id_INDUSTRY)
);

CREATE TABLE SCHOOL(
   Id_SCHOOL COUNTER,
   PRIMARY KEY(Id_SCHOOL)
);

CREATE TABLE ADMIN(
   idUser VARCHAR(30),
   PRIMARY KEY(idUser),
   FOREIGN KEY(idUser) REFERENCES APP_USER(idUser)
);

CREATE TABLE Accomplish(
   Id_PROJECT INT,
   idUser VARCHAR(30) NOT NULL,
   PRIMARY KEY(Id_PROJECT),
   FOREIGN KEY(Id_PROJECT) REFERENCES PROJECT(Id_PROJECT),
   FOREIGN KEY(idUser) REFERENCES STUDENT(idUser)
);

CREATE TABLE Asso_8(
   idUser VARCHAR(30),
   Id_INDUSTRY INT,
   PRIMARY KEY(idUser, Id_INDUSTRY),
   FOREIGN KEY(idUser) REFERENCES COMPANY(idUser),
   FOREIGN KEY(Id_INDUSTRY) REFERENCES INDUSTRY(Id_INDUSTRY)
);

CREATE TABLE concern(
   idUser VARCHAR(30),
   Id_INDUSTRY INT,
   PRIMARY KEY(idUser, Id_INDUSTRY),
   FOREIGN KEY(idUser) REFERENCES STUDENT(idUser),
   FOREIGN KEY(Id_INDUSTRY) REFERENCES INDUSTRY(Id_INDUSTRY)
);

CREATE TABLE is_part_of(
   idUser VARCHAR(30),
   Id_SCHOOL INT,
   PRIMARY KEY(idUser, Id_SCHOOL),
   FOREIGN KEY(idUser) REFERENCES STUDENT(idUser),
   FOREIGN KEY(Id_SCHOOL) REFERENCES SCHOOL(Id_SCHOOL)
);
